Добавляет функции для коментариев
htmlacademy-javascript/1966385-kekstagram-30 pull request #4
Opened 2023-10-18 18:17 UTC by kol5ack

2023-10-20 06:03 UTC, kenakula requested changes

2023-10-20 06:03 UTC, kenakula commented on js/main.js
> +}
данная функция не запоминает уже созданные айдишники, в массиве созданных объектов они могут повторяться, это нежелательное поведение

2023-10-23 12:15 UTC, kenakula approved these changes

2023-10-23 19:05 UTC, kol5ack commented
Исправляет конфликт

2023-10-23 19:05 UTC, merged