Добавляет миниатюры
htmlacademy-javascript/1966385-kekstagram-30 pull request #6
Opened 2023-11-01 19:27 UTC by kol5ack

2023-11-01 19:29 UTC, kol5ack commented on js/util.js
> +  urlPhoto: `photos/{${generatePhoto}}.jpg`,
У меня почем-то не отрисовываются картинки, когда запускаю проект. Без мастера не обойтись. Вообще без понятия.

2023-11-01 20:01 UTC, kenakula requested changes

2023-11-01 20:01 UTC, kenakula commented on js/thumbnail.js
> +  querySelector('.picture');
если хочется перенести, то переноси вместе с точкой, так лучше читается, тут можно даже не переносить, места хватает, нормально будет

2023-11-01 20:01 UTC, kenakula commented on js/thumbnail.js
> +
ту мач, одной строки отступа достаточно)

2023-11-01 20:01 UTC, kenakula commented on js/thumbnail.js
> +  pictures.forEach((picture) => {
отступи плз одну строку от объявления переменной

2023-11-01 20:01 UTC, kenakula commented on js/util.js
> +  urlPhoto: `photos/{${generatePhoto}}.jpg`,
у тебя тут название свойства объекта urlPhoto, а в функции где ты берешь это значение и вставляешь в src, ты обращаешься к свойству url, его в объекте нет, поэтому в src записывается undefined

2023-11-03 04:41 UTC, kenakula approved these changes

2023-11-03 15:49 UTC, kenakula approved these changes

2023-11-06 17:45 UTC, merged